# Configuration for Travis CI
language: cpp
os: linux
sudo: required
dist: xenial
cache: ccache

before_install:
    - sudo apt-get -y install cmake libsdl2-dev libsdl2-mixer-dev libxrandr-dev libxxf86vm-dev libfluidsynth-dev ncurses-dev

before_script:
    - mkdir build-travis

script:
    - cd build-travis && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDE_ENABLE_TESTS=ON ../doomsday && make -j4
